# Generated by Django 3.0 on 2019-12-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
