# Generated by Django 3.0 on 2019-12-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_rank_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
