# Generated by Django 3.0 on 2019-12-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_shopping_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
